# Generated by Django 4.0.3 on 2022-04-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='automoviles')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.marca')),
            ],
        ),
    ]
