# Generated by Django 4.0.3 on 2022-04-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
