# Generated by Django 4.0.3 on 2022-04-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_automovil_marca_delete_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='imagen',
            field=models.ImageField(blank=True, default='automoviles/lujo.jpg', null=True, upload_to='automoviles'),
        ),
    ]
