# Generated by Django 4.0.3 on 2022-04-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_automovil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='automoviles'),
        ),
    ]
